# Generated by Django 4.2.4 on 2023-08-04 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lijiang_guide", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafe",
            name="cafe_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="hiking",
            name="trail_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
