# Generated by Django 4.2.4 on 2023-08-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lijiang_guide", "0002_cafe_cafe_image_hiking_trail_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafe",
            name="cafe_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="hiking",
            name="trail_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
