# Generated by Django 4.2.4 on 2023-08-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lijiang_guide", "0003_alter_cafe_cafe_image_alter_hiking_trail_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hiking",
            name="trail_image",
        ),
        migrations.AddField(
            model_name="hiking",
            name="hiking_image",
            field=models.ImageField(blank=True, null=True, upload_to="hiking_images/"),
        ),
        migrations.AlterField(
            model_name="cafe",
            name="cafe_image",
            field=models.ImageField(blank=True, null=True, upload_to="cafe_images/"),
        ),
    ]
