# Generated by Django 4.2.4 on 2023-08-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lijiang_guide", "0006_alter_trailreview_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trailreview",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
