# Generated by Django 4.2.4 on 2023-08-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lijiang_guide", "0010_hiking_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("location", models.CharField(max_length=250)),
                ("map", models.URLField()),
                (
                    "rental_main",
                    models.ImageField(blank=True, null=True, upload_to="rental_images"),
                ),
                (
                    "living_room",
                    models.ImageField(blank=True, null=True, upload_to="rental_images"),
                ),
                (
                    "bedroom",
                    models.ImageField(blank=True, null=True, upload_to="rental_images"),
                ),
                (
                    "bathroom",
                    models.ImageField(blank=True, null=True, upload_to="rental_images"),
                ),
            ],
        ),
    ]
