# Generated by Django 4.2.4 on 2023-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lijiang_guide", "0012_remove_trailreview_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailreview",
            name="star_rating",
            field=models.IntegerField(default=0),
        ),
    ]
