# Generated by Django 4.2.4 on 2023-08-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lijiang_guide", "0014_alter_trailreview_star_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trailreview",
            name="star_rating",
            field=models.IntegerField(default=None),
        ),
    ]
